name: dpsv
type: nodejs:4.2

web:
    commands:
        start: "SOURCES_FOLDER=~/sources npm run web &>> logs/web.log"

    locations:
        "/static":
            root: "static"
            passthru: true
            expires: 1w

disk: 4096

mounts:
    "/sources": "shared:files/sources"
    "/logs": "shared:files/logs"

relationships:
    database: "postgresql:postgresql"

hooks:
    build: |
        npm install
        npm run build

crons:
    updater:
        spec: "0 4 * * *"
        cmd: "npm run updater &>> logs/updater.log"
    deleter:
        spec: "0 * * * *"
        cmd: "npm run deleter &>> logs/deleter.log"
